"""
Φ‑QML ↔ Φ‑Kovy 3.0 Integration — Autonomous idea‑to‑code pipeline

Connects the Φ‑Kovy ideation engine with Φ‑QML execution layer.
Φ‑Kovy generates ideas, Φ‑QML implements them, EleganceTracker
evaluates them, and Φ‑Kovy learns from the results to generate
better ideas in the next iteration.

This creates a closed‑loop autonomous research system.
"""

import time
import json
import secrets
from typing import Any, Dict, List, Optional, Tuple
from dataclasses import dataclass, field

from phi_qml.interpreter import Interpreter
from phi_qml.lexer import Lexer
from phi_qml.parser import Parser
from phi_qml.elegance_tracker import EleganceTracker


@dataclass
class Idea:
    """An idea generated by Φ‑Kovy."""
    title: str
    description: str
    primitives: List[str]
    estimated_phi: float
    source: str = ""
    timestamp: float = field(default_factory=time.time)


class PhiKovyBridge:
    """
    Bridge between Φ‑Kovy 3.0 and Φ‑QML.

    Implements the autonomous loop:
    1. Φ‑Kovy generates an idea
    2. Φ‑QML implements it as a program
    3. EleganceTracker evaluates the implementation
    4. Φ‑Kovy learns from the result
    5. Repeat with improved ideas
    """

    def __init__(self, mode: str = "quantum"):
        self.mode = mode
        self.ideas: List[Idea] = []
        self.implementations: List[Dict] = []
        self.elegance_history: List[float] = []
        self.tracker = EleganceTracker(min_phi=0.3)
        self.iteration = 0

        # Knowledge base of primitives and their Φ scores
        self.primitive_scores = {
            "SubstrateModulo": 1.0,
            "HolographicField": 0.95,
            "SubstrateSearch": 1.0,
            "QFT": 0.7,
            "GroverSearch": 0.6,
            "VQE": 0.4,
            "ClassicalSearch": 0.1,
            "ClassicalSort": 0.05,
        }

        # Idea templates that Φ‑Kovy can combine
        self.idea_templates = {
            "quantum": [
                {
                    "title": "Substrate* Factorization",
                    "primitives": ["SubstrateModulo", "QFT", "HolographicField"],
                    "base_phi": 0.95,
                },
                {
                    "title": "Quantum Neural Network",
                    "primitives": ["VQE", "HolographicField"],
                    "base_phi": 0.3,
                },
                {
                    "title": "Holographic Database",
                    "primitives": ["SubstrateSearch", "HolographicField"],
                    "base_phi": 0.9,
                },
            ],
            "crypto": [
                {
                    "title": "Quantum‑Resistant Signature",
                    "primitives": ["SubstrateModulo"],
                    "base_phi": 0.85,
                },
            ],
            "optimization": [
                {
                    "title": "Portfolio Optimizer",
                    "primitives": ["GroverSearch", "VQE"],
                    "base_phi": 0.5,
                },
            ],
        }

    def generate_idea(self) -> Idea:
        """Φ‑Kovy generates a new idea based on current knowledge."""
        templates = self.idea_templates.get(self.mode, self.idea_templates["quantum"])

        # Prefer higher‑Φ ideas as the system learns
        weights = []
        for t in templates:
            weight = t["base_phi"]
            # Boost ideas using primitives that performed well
            for p in t["primitives"]:
                weight += self.primitive_scores.get(p, 0.5) * 0.1
            weights.append(weight)

        # Select template
        total = sum(weights)
        r = secrets.SystemRandom().random() * total
        cumulative = 0
        selected = templates[0]
        for t, w in zip(templates, weights):
            cumulative += w
            if r <= cumulative:
                selected = t
                break

        # Generate source code for the idea
        source = self._generate_source(selected)

        idea = Idea(
            title=selected["title"],
            description=f"Autonomous idea #{self.iteration}: {selected['title']}",
            primitives=selected["primitives"],
            estimated_phi=selected["base_phi"],
            source=source,
        )
        self.ideas.append(idea)
        return idea

    def _generate_source(self, template: Dict) -> str:
        """Generate Φ‑QML source code for an idea template."""
        title = template["title"]
        if "Modulo" in title or "mod" in title.lower():
            return """
fn main() {
    let a = 2^256 + 123456789;
    let n = 997;
    let r = mod(a, n);
    println("mod result: " + r);
}
"""
        elif "Search" in title:
            return """
fn main() {
    let data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
    let target = 7;
    let field: field<8> = init_field();
    for i in 0..10 {
        field.write(i, data[i]);
    }
    let result = field.read(target);
    println("Found: " + result);
}
"""
        else:
            return """
fn main() {
    println("Implementing: """ + title + """);
    let q0: qubit = |0>;
    let h = H(q0);
    let m = measure(h);
    println("Result: " + m);
}
"""

    def implement_idea(self, idea: Idea) -> Dict:
        """Φ‑QML implements the idea by executing the generated source."""
        try:
            lexer = Lexer(idea.source)
            tokens = lexer.tokenize()
            parser = Parser(tokens)
            ast = parser.parse()
            interpreter = Interpreter()

            import sys, io
            old_stdout = sys.stdout
            sys.stdout = captured = io.StringIO()
            interpreter.interpret(ast)
            output = captured.getvalue()
            captured.close()
            sys.stdout = old_stdout

            phi = interpreter.tracker.get_average_phi()
            debt = interpreter.tracker.get_elegance_debt()

            impl = {
                "idea": idea.title,
                "source": idea.source,
                "output": output,
                "phi": phi,
                "debt": debt,
                "success": True,
            }
        except Exception as e:
            impl = {
                "idea": idea.title,
                "source": idea.source,
                "output": str(e),
                "phi": 0.0,
                "debt": 1.0,
                "success": False,
            }

        self.implementations.append(impl)
        self.elegance_history.append(impl["phi"])
        return impl

    def learn_from_result(self, impl: Dict):
        """Φ‑Kovy learns from the implementation result."""
        # Update primitive scores based on performance
        if impl["success"] and impl["phi"] > 0.5:
            # Successful implementation �� boost related primitives
            for idea in self.ideas[-1:]:
                for p in idea.primitives:
                    if p in self.primitive_scores:
                        self.primitive_scores[p] = min(1.0, self.primitive_scores[p] + 0.05)
        else:
            # Failed or inelegant — reduce scores
            for idea in self.ideas[-1:]:
                for p in idea.primitives:
                    if p in self.primitive_scores:
                        self.primitive_scores[p] = max(0.01, self.primitive_scores[p] - 0.03)

    def run_iteration(self) -> Dict:
        """Execute one complete iteration of the autonomous loop."""
        self.iteration += 1
        idea = self.generate_idea()
        impl = self.implement_idea(idea)
        self.learn_from_result(impl)
        return {
            "iteration": self.iteration,
            "idea": idea.title,
            "phi": impl["phi"],
            "success": impl["success"],
        }

    def run_loop(self, iterations: int = 5, verbose: bool = True) -> List[Dict]:
        """Run multiple iterations of the autonomous loop."""
        results = []
        for i in range(iterations):
            result = self.run_iteration()
            results.append(result)
            if verbose:
                status = "✅" if result["success"] else "❌"
                phi_str = f"{result['phi']:.3f}" if result['phi'] != float('inf') else "∞"
                print(f"  {i+1}. {status} {result['idea']} — Φ = {phi_str}")
        return results

    def get_learning_report(self) -> Dict:
        """Report on what the system has learned."""
        if not self.elegance_history:
            return {"status": "No learning data yet"}
        return {
            "iterations": len(self.elegance_history),
            "avg_phi": sum(self.elegance_history) / len(self.elegance_history),
            "best_phi": max(self.elegance_history),
            "improving": (
                self.elegance_history[-1] > self.elegance_history[0]
                if len(self.elegance_history) >= 2 else None
            ),
            "top_primitives": sorted(
                self.primitive_scores.items(),
                key=lambda x: x[1], reverse=True
            )[:5],
        }
